In [2]:
import numpy as np

In [3]:
#Q1
array1=np.array([[1,2,3],[4,5,6]])
print(array1.tolist())

[[1, 2, 3], [4, 5, 6]]


In [22]:
#Q2
x = np.arange(9)
m=x.reshape(3,3)
print(m)
result =  np.trace(m)
print("the sum of the diagonal elements is:",result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
the sum of the diagonal elements is: 12


In [42]:
#Q3
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Values bigger than 20 =", x[x>20])

Values bigger than 20 = [30 40]


In [34]:
#Q4
a=np.array([5,2,7])
b=np.array([5,8,3])
c=a+b
print(c)

[10 10 10]


In [39]:
#Q5
x=np.array([10,10,10])
y=x.mean()
print(y)
c=x-y
print(c)

10.0
[0. 0. 0.]
